before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: arashnrim
      name: homebrew-tap
    commit_author:
      name: Arash
      email: "47273556+arashnrim@users.noreply.github.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    homepage: "https://github.com/arashnrim/tp"
    description: "⚡️ Teleport to your projects and run commands in an instant."
    license: "MIT"
    skip_upload: auto
    install: bin.install "tp"
